name: context_menu
description: Contexual menu.
version: 0.0.2
repository: "https://github.com/helpisdev/context_menu.git"
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  after_layout: ^1.2.0
  animations: ^2.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
